
/**
 *
 * @author Hadassah
 */
public class frmGuiDemo extends javax.swing.JFrame {

    /**
     * Creates new form frmGuiDemo
     */
    public frmGuiDemo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfDollar = new javax.swing.JTextField();
        btnEuro = new javax.swing.JButton();
        tfEuro = new javax.swing.JTextField();
        btnGBP = new javax.swing.JButton();
        tfGBP = new javax.swing.JTextField();
        btnYen = new javax.swing.JButton();
        tfYen = new javax.swing.JTextField();
        btnNIS = new javax.swing.JButton();
        tfNIS = new javax.swing.JTextField();
        btnDollar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        crEuro = new javax.swing.JTextField();
        crGBP = new javax.swing.JTextField();
        crYen = new javax.swing.JTextField();
        crNIS = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(51, 153, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Maiandra GD", 1, 36)); // NOI18N
        jLabel1.setText("Currency Converter");

        btnEuro.setBackground(new java.awt.Color(0, 102, 153));
        btnEuro.setForeground(new java.awt.Color(255, 255, 255));
        btnEuro.setText("EURO");
        btnEuro.setOpaque(false);
        btnEuro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEuroMouseClicked(evt);
            }
        });

        tfEuro.setText(" ");

        btnGBP.setBackground(new java.awt.Color(0, 102, 153));
        btnGBP.setForeground(new java.awt.Color(255, 255, 255));
        btnGBP.setText("GBP");
        btnGBP.setOpaque(false);
        btnGBP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGBPMouseClicked(evt);
            }
        });

        tfGBP.setText(" ");

        btnYen.setBackground(new java.awt.Color(0, 102, 153));
        btnYen.setForeground(new java.awt.Color(255, 255, 255));
        btnYen.setText("Yen");
        btnYen.setOpaque(false);
        btnYen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnYenMouseClicked(evt);
            }
        });

        tfYen.setText(" ");

        btnNIS.setBackground(new java.awt.Color(0, 102, 153));
        btnNIS.setForeground(new java.awt.Color(255, 255, 255));
        btnNIS.setText("NIS");
        btnNIS.setOpaque(false);
        btnNIS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNISMouseClicked(evt);
            }
        });

        tfNIS.setText(" ");

        btnDollar.setBackground(new java.awt.Color(0, 102, 153));
        btnDollar.setForeground(new java.awt.Color(255, 255, 255));
        btnDollar.setText("DOLLAR");
        btnDollar.setOpaque(false);
        btnDollar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDollarMouseClicked(evt);
            }
        });

        jLabel3.setText("$/Euro");

        jLabel4.setText("$/GBP");

        jLabel5.setText("Yen/S");

        jLabel6.setText("NIS/$");

        crEuro.setText("0.88");
        crEuro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                crEuroKeyTyped(evt);
            }
        });

        crGBP.setText("0.79");
        crGBP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                crGBPKeyTyped(evt);
            }
        });

        crYen.setText("109.12");
        crYen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                crYenKeyTyped(evt);
            }
        });

        crNIS.setText("3.45");
        crNIS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                crNISKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jLabel3)
                        .addGap(70, 70, 70)
                        .addComponent(jLabel4)
                        .addGap(78, 78, 78)
                        .addComponent(jLabel5)
                        .addGap(74, 74, 74)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfDollar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDollar))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnEuro, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfEuro, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnGBP, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfGBP, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfYen, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnYen, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(btnNIS, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfNIS, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(crEuro, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(crGBP, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(crYen, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(crNIS, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNIS)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(tfDollar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(tfNIS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEuro)
                            .addComponent(btnGBP)
                            .addComponent(btnDollar)
                            .addComponent(btnYen))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfEuro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfGBP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfYen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crEuro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(crGBP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(crYen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(crNIS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void crEuroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_crEuroKeyTyped
        try {
            double rate = Double.parseDouble(crEuro.getText());
            double dollars = Double.parseDouble(tfDollar.getText());
            double nwEuro = rate * dollars;
            tfEuro.setText(String.format("%.2f", nwEuro));
        } catch (Exception e) {
            tfEuro.setText(" ");
        }

    }//GEN-LAST:event_crEuroKeyTyped

    private void crGBPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_crGBPKeyTyped
        try {
            double rate = Double.parseDouble(crGBP.getText());
            double dollars = Double.parseDouble(tfDollar.getText());
            double nwGBP = rate * dollars;
            tfGBP.setText(String.format("%.2f", nwGBP));
        } catch (Exception e) {
            tfGBP.setText(" ");
        }

    }//GEN-LAST:event_crGBPKeyTyped

    private void crYenKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_crYenKeyTyped
        try {
            double rate = Double.parseDouble(crYen.getText());
            double dollars = Double.parseDouble(tfDollar.getText());
            double nwYen = rate * dollars;
            tfYen.setText(String.format("%.2f", nwYen));
        } catch (Exception e) {
            tfYen.setText(" ");
        }
    }//GEN-LAST:event_crYenKeyTyped

    private void crNISKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_crNISKeyTyped
        try {
            double rate = Double.parseDouble(crNIS.getText());
            double dollars = Double.parseDouble(tfDollar.getText());
            double nwNIS = rate * dollars;
            tfNIS.setText(String.format("%.2f", nwNIS));
        } catch (Exception e) {
            tfNIS.setText(" ");
        }
    }//GEN-LAST:event_crNISKeyTyped

    private void btnDollarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDollarMouseClicked

        try {
            double dollar = Double.parseDouble(tfDollar.getText());

            double euro = dollar * Double.parseDouble(crEuro.getText());
            tfEuro.setText(String.format("%.2f", euro));

            double gbp = dollar * Double.parseDouble(crGBP.getText());
            tfGBP.setText(String.format("%.2f", gbp));

            double yen = dollar * Double.parseDouble(crYen.getText());
            tfYen.setText(String.format("%.2f", yen));

            double nis = dollar * Double.parseDouble(crNIS.getText());
            tfNIS.setText(String.format("%.2f", nis));

        } catch (Exception e) {
            tfDollar.setText("");
        }

    }//GEN-LAST:event_btnDollarMouseClicked

    private void btnEuroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEuroMouseClicked
        try {
            double euro = Double.parseDouble(tfEuro.getText());

            double dollar = euro / Double.parseDouble(crEuro.getText());
            tfDollar.setText(String.format("%.2f", dollar));

            double gbp = dollar * Double.parseDouble(crGBP.getText());
            tfGBP.setText(String.format("%.2f", gbp));

            double yen = dollar * Double.parseDouble(crYen.getText());
            tfYen.setText(String.format("%.2f", yen));

            double nis = dollar * Double.parseDouble(crNIS.getText());
            tfNIS.setText(String.format("%.2f", nis));

        } catch (Exception e) {
            tfEuro.setText("");
        }
    }//GEN-LAST:event_btnEuroMouseClicked

    private void btnGBPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGBPMouseClicked
        try {
            double gbp = Double.parseDouble(tfGBP.getText());

            double dollar = gbp / Double.parseDouble(crGBP.getText());
            tfDollar.setText(String.format("%.2f", dollar));

            double euro = dollar * Double.parseDouble(crEuro.getText());
            tfEuro.setText(String.format("%.2f", euro));

            double yen = dollar * Double.parseDouble(crYen.getText());
            tfYen.setText(String.format("%.2f", yen));

            double nis = dollar * Double.parseDouble(crNIS.getText());
            tfNIS.setText(String.format("%.2f", nis));

        } catch (Exception e) {
            tfGBP.setText(" ");
        }    }//GEN-LAST:event_btnGBPMouseClicked

    private void btnYenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnYenMouseClicked
        try {
            double yen = Double.parseDouble(tfYen.getText());

            double dollar = yen / Double.parseDouble(crYen.getText());
            tfDollar.setText(String.format("%.2f", dollar));

            double euro = dollar * Double.parseDouble(crEuro.getText());
            tfEuro.setText(String.format("%.2f", euro));

            double gbp = dollar * Double.parseDouble(crGBP.getText());
            tfGBP.setText(String.format("%.2f", gbp));

            double nis = dollar * Double.parseDouble(crNIS.getText());
            tfNIS.setText(String.format("%.2f", nis));

        } catch (Exception e) {
            tfYen.setText("");
        }    }//GEN-LAST:event_btnYenMouseClicked

    private void btnNISMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNISMouseClicked
        try {
            double nis = Double.parseDouble(tfNIS.getText());

            double dollar = nis / Double.parseDouble(crNIS.getText());
            tfDollar.setText(String.format("%.2f", dollar));

            double yen = dollar * Double.parseDouble(crYen.getText());
            tfYen.setText(String.format("%.2f", yen));

            double euro = dollar * Double.parseDouble(crEuro.getText());
            tfEuro.setText(String.format("%.2f", euro));

            double gbp = dollar * Double.parseDouble(crGBP.getText());
            tfGBP.setText(String.format("%.2f", gbp));

        } catch (Exception e) {
            tfNIS.setText("");
        }    }//GEN-LAST:event_btnNISMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmGuiDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmGuiDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmGuiDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmGuiDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmGuiDemo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDollar;
    private javax.swing.JButton btnEuro;
    private javax.swing.JButton btnGBP;
    private javax.swing.JButton btnNIS;
    private javax.swing.JButton btnYen;
    private javax.swing.JTextField crEuro;
    private javax.swing.JTextField crGBP;
    private javax.swing.JTextField crNIS;
    private javax.swing.JTextField crYen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField tfDollar;
    private javax.swing.JTextField tfEuro;
    private javax.swing.JTextField tfGBP;
    private javax.swing.JTextField tfNIS;
    private javax.swing.JTextField tfYen;
    // End of variables declaration//GEN-END:variables
}
